name: Renovate

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      logLevel:
        required: false
        default: info
        type: choice
        options: [trace, debug, info, warn, error, fatal]

permissions:
  contents: read

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.RENOVATE_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: Renovate
        uses: renovatebot/github-action@5402b206248e5a8c8427a15102702eb9c1793efc # v46.2.4
        env:
          RENOVATE_TOKEN: ${{ steps.app-token.outputs.token }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
